name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "BASE_URL='https://qa-challange.netlify.app/'" > .env

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Set environment variables
        run: |
          echo "SEED_PHRASE=${{ secrets.SEED_PHRASE }}" >> .env
          echo "METAMASK_PASSWORD=${{ secrets.METAMASK_PASSWORD }}" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Build Cache
        run: npm run build:cache

      - name: Build Cache Headless
        run: npm run build:cache:headless